name: Test SQL Functions

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'supabase/migrations/**'
      - 'supabase/tests/**'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'supabase/migrations/**'
      - 'supabase/tests/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Supabase CLI
      uses: supabase/setup-cli@v1
      with:
        version: latest
    
    - name: Start Supabase local instance
      run: |
        supabase start || true
        echo "Supabase started"
        supabase status
      timeout-minutes: 5
    
    - name: Run SQL function tests
      run: |
        DB_HOST=localhost
        DB_PORT=$(supabase status | grep 'DB URL' | sed -n 's/.*postgresql:\/\/postgres:postgres@127.0.0.1:\([0-9]*\)\/.*/\1/p')
        DB_NAME=postgres
        DB_USER=postgres
        DB_PASSWORD=postgres
        export DB_HOST DB_PORT DB_NAME DB_USER DB_PASSWORD
        chmod +x supabase/tests/run_tests.sh
        ./supabase/tests/run_tests.sh
      timeout-minutes: 5
    
    - name: Stop Supabase
      if: always()
      run: supabase stop
    
    - name: Test Summary
      if: always()
      run: echo "SQL function tests completed"
